In [51]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

In [52]:
fish = pd.read_csv('data/fish.csv')
fish.head()

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [53]:
pd.unique(fish['Species'])
# fish.shape
# fish.info()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [54]:
fish_input = fish[['Weight','Length','Diagonal','Height','Width']].to_numpy()
fish_target = fish['Species'].to_numpy()

print(fish_input.shape, fish_target.shape)

(159, 5) (159,)


In [55]:
# fish_input.info() 안됨 pandas
fish_input[:5]

array([[242.    ,  25.4   ,  30.    ,  11.52  ,   4.02  ],
       [290.    ,  26.3   ,  31.2   ,  12.48  ,   4.3056],
       [340.    ,  26.5   ,  31.1   ,  12.3778,   4.6961],
       [363.    ,  29.    ,  33.5   ,  12.73  ,   4.4555],
       [430.    ,  29.    ,  34.    ,  12.444 ,   5.134 ]])

In [56]:
X_train, X_test, y_train, y_test = train_test_split(\
    fish_input, fish_target, random_state=42)

In [57]:
print(X_train.shape, X_test.shape)

(119, 5) (40, 5)


## 정규화

In [58]:
ss = StandardScaler()
ss.fit(X_train)
X_train_scaled = ss.transform(X_train)
X_test_scaled = ss.transform(X_test)

In [59]:
print(X_train_scaled[:5])

[[ 0.91965782  0.60943175  0.81041221  1.85194896  1.00075672]
 [ 0.30041219  1.54653445  1.45316551 -0.46981663  0.27291745]
 [-1.0858536  -1.68646987 -1.70848587 -1.70159849 -2.0044758 ]
 [-0.79734143 -0.60880176 -0.67486907 -0.82480589 -0.27631471]
 [-0.71289885 -0.73062511 -0.70092664 -0.0802298  -0.7033869 ]]


In [60]:
kn = KNeighborsClassifier(n_neighbors=3)
kn.fit(X_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=3)

In [61]:
# probablity 확률
proba = kn.predict_proba(X_test_scaled[:5])
print(proba)

[[0.         0.         1.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         0.         1.
  0.        ]
 [0.         0.         0.         1.         0.         0.
  0.        ]
 [0.         0.         0.66666667 0.         0.33333333 0.
  0.        ]
 [0.         0.         0.66666667 0.         0.33333333 0.
  0.        ]]


In [62]:
kn.classes_

array(['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'],
      dtype=object)

In [63]:
print(kn.score(X_train_scaled, y_train))
print(kn.score(X_test_scaled, y_test))

0.8907563025210085
0.85


In [64]:
print(np.round(proba,decimals=4))

[[0.     0.     1.     0.     0.     0.     0.    ]
 [0.     0.     0.     0.     0.     1.     0.    ]
 [0.     0.     0.     1.     0.     0.     0.    ]
 [0.     0.     0.6667 0.     0.3333 0.     0.    ]
 [0.     0.     0.6667 0.     0.3333 0.     0.    ]]


In [65]:
distances, indexes = kn.kneighbors(X_test_scaled[3:4])
print(y_train[indexes])

[['Roach' 'Perch' 'Perch']]


In [66]:
# pd.DataFrame(y_train).value_counts()
(y_train == "Bream").sum()

np.int64(24)

In [67]:
bream_smelt_indexes = (y_train == "Bream") | (y_train=="Smelt")
bream_smelt_indexes.sum()

train_bream_smelt = X_train_scaled[bream_smelt_indexes]
train_bream_smelt.shape
target_bream_smelt = y_train[bream_smelt_indexes]

print(train_bream_smelt.shape, target_bream_smelt.shape)

(33, 5) (33,)


In [68]:
lr = LogisticRegression()
lr.fit(train_bream_smelt, target_bream_smelt)

LogisticRegression()

In [70]:
print(lr.score(train_bream_smelt, target_bream_smelt))
# print(lr.score(X_test_scaled,y_test))

1.0


In [72]:
print(lr.predict(train_bream_smelt[:5]))
print(lr.predict_proba(train_bream_smelt[:5]))
print(lr.classes_)

['Bream' 'Smelt' 'Bream' 'Bream' 'Bream']
[[0.99760007 0.00239993]
 [0.02737325 0.97262675]
 [0.99486386 0.00513614]
 [0.98585047 0.01414953]
 [0.99767419 0.00232581]]
['Bream' 'Smelt']


In [73]:
print(lr.coef_, lr.intercept_)

[[-0.40451732 -0.57582787 -0.66248158 -1.01329614 -0.73123131]] [-2.16172774]


In [ ]:
# 결정점수 decision score z > 0 -> 1 , z < 0 -> 0
decisions = lr.decision_function(train_bream_smelt[:5])
print(decisions)

# sigmode 함수적용 0, 1, 0, 0, 0  z > 0.5 -> 1, < 0.5 -> 0
from scipy.special import expit
proba = expit(decisions)
print(proba)

[-6.02991358  3.57043428 -5.26630496 -4.24382314 -6.06135688]
[0.00239993 0.97262675 0.00513614 0.01414953 0.00232581]


In [75]:
lr = LogisticRegression(C=20,max_iter=1000)
lr.fit(X_train_scaled, y_train)
print(lr.score(X_test_scaled,y_test))

0.925


In [77]:
print(lr.predict(X_test_scaled[:5]))

['Perch' 'Smelt' 'Pike' 'Roach' 'Perch']


In [79]:
proba = lr.predict_proba(X_test_scaled[:5])
print(np.round(proba,decimals=3))
print(lr.classes_)

[[0.    0.014 0.842 0.    0.135 0.007 0.003]
 [0.    0.003 0.044 0.    0.007 0.946 0.   ]
 [0.    0.    0.034 0.934 0.015 0.016 0.   ]
 [0.011 0.034 0.305 0.006 0.567 0.    0.076]
 [0.    0.    0.904 0.002 0.089 0.002 0.001]]
['Bream' 'Parkki' 'Perch' 'Pike' 'Roach' 'Smelt' 'Whitefish']


In [82]:
print(lr.coef_,lr.intercept_)
print(lr.coef_.shape,lr.intercept_.shape)

[[-1.50605455 -1.03747913  2.60919713  7.69422739 -1.18603342]
 [ 0.19200047 -1.99988812 -3.79617725  6.50312639 -2.00022754]
 [ 3.55793539  6.36988929 -8.52233732 -5.75397233  3.79233438]
 [-0.11453308  3.61060121  3.94464503 -3.62243904 -1.7598168 ]
 [-1.40843717 -6.09242191  5.28629633 -0.86696569  1.84518455]
 [-1.33419952  1.48153392  1.38217547 -5.6602348  -4.39228963]
 [ 0.61328846 -2.33223527 -0.90379939  1.70625807  3.70084846]] [-0.10345045 -0.27281217  3.24444852 -0.17565069  2.64960025 -6.72042852
  1.37829306]
(7, 5) (7,)


In [83]:
decision = lr.decision_function(X_test_scaled[:5])
print(np.round(decision,decimals=2))

[[ -6.51   1.04   5.17  -2.76   3.34   0.35  -0.63]
 [-10.88   1.94   4.78  -2.42   2.99   7.84  -4.25]
 [ -4.34  -6.24   3.17   6.48   2.36   2.43  -3.87]
 [ -0.69   0.45   2.64  -1.21   3.26  -5.7    1.26]
 [ -6.4   -1.99   5.82  -0.13   3.5   -0.09  -0.7 ]]


In [ ]:
# softmax 데이터 총합이 1이 되는 확률값으로 반환
from scipy.special import softmax
proba = softmax(decision, axis=1)
print(np.round(proba,decimals=3))

[[0.    0.014 0.842 0.    0.135 0.007 0.003]
 [0.    0.003 0.044 0.    0.007 0.946 0.   ]
 [0.    0.    0.034 0.934 0.015 0.016 0.   ]
 [0.011 0.034 0.305 0.006 0.567 0.    0.076]
 [0.    0.    0.904 0.002 0.089 0.002 0.001]]


## 최종 목적 : 모델 최적화