In [46]:
import tensorflow as tf
import numpy as np

In [47]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.losses import mse
from tensorflow.keras.optimizers import Adam

1. 단층퍼셉트론으로 0r게이트 구현

|x1|x2|y|
|---|---|---|
|0|0|0|
|1|0|1|
|0|1|1|
|1|1|1|

In [48]:
data =np.array([[0,0], [0,1], [1,0], [1,1]])

label = np.array([0,1,1,1])

In [49]:
model = Sequential()
model.add(Dense(1, input_shape=(2,)))

c:\lys\03python\02code\01test\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [50]:
model.compile(
    optimizer=Adam(),
    loss=mse,
    metrics=['acc']
)

In [51]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3 (12.00 B)

 Trainable params: 3 (12.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(data, label, epochs=500,verbose=0)

Epoch 1/500


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 602ms/step - acc: 0.2500 - loss: 3.4411
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - acc: 0.2500 - loss: 3.4335
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - acc: 0.2500 - loss: 3.4260
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - acc: 0.2500 - loss: 3.4185
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - acc: 0.2500 - loss: 3.4110
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - acc: 0.2500 - loss: 3.4035
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - acc: 0.2500 - loss: 3.3960
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - acc: 0.2500 - loss: 3.3885
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - acc: 0.2500 - loss: 3.3810
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - acc: 0.2500 - loss: 3.3736
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - acc: 0.2500 - loss: 3.3661
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - acc: 0.2500 - loss: 3.3587
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - acc: 0.

In [53]:
model.get_weights()

[array([[-0.80140084],
        [ 0.04539004]], dtype=float32),
 array([0.41957015], dtype=float32)]

In [54]:
print(model.predict(data))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
[[ 0.41957015]
 [ 0.4649602 ]
 [-0.3818307 ]
 [-0.33644068]]


2. xor 게이트

In [55]:
data =np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
    ])

label = np.array([0,1,1,0])

In [58]:
model = Sequential()
model.add(Dense(32, input_shape=(2,), activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.compile(
    optimizer=Adam(),
    loss=mse,
    metrics=['acc']
)

In [59]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 32)             │            96 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 129 (516.00 B)

 Trainable params: 129 (516.00 B)

 Non-trainable params: 0 (0.00 B)

In [60]:
model.fit(data, label, epochs=500, verbose=0)

In [62]:
model.evaluate(data, label)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - acc: 1.0000 - loss: 0.0630


[0.06299325078725815, 1.0]

In [63]:
print(model.predict(data))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
[[0.26469225]
 [0.7547956 ]
 [0.7514477 ]
 [0.24496444]]
