In [53]:
from warnings import filterwarnings
filterwarnings("ignore")

import tensorflow as tf
import numpy as np

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
# from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam

|x1|x2|y|
|---|---|---|
|0|0|0|
|1|0|1|
|0|1|1|
|1|1|1|

In [36]:
data = np.array([
    [0,0],
    [1,0],
    [0,1],
    [1,1]
])

In [37]:
label = np.array([0,0,0,1])

In [38]:
# 모델구성
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(1,input_shape=(2,)))
# model = Sequential()
# model.add(Dense(1,input_shape=(2,)))

In [39]:
# 컴파일
model.compile(
    optimizer = "sgd",
    # optimizer = SGD()
    loss='mse',
    # loss = MSE()
    metrics = ["acc"]
)

In [40]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_5 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3 (12.00 B)

 Trainable params: 3 (12.00 B)

 Non-trainable params: 0 (0.00 B)

In [41]:
# 모델학습
model.fit(data,label,epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 748ms/step - acc: 0.5000 - loss: 0.9625
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - acc: 0.5000 - loss: 0.9461
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - acc: 0.5000 - loss: 0.9304
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - acc: 0.5000 - loss: 0.9153
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - acc: 0.5000 - loss: 0.9007
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - acc: 0.5000 - loss: 0.8867
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - acc: 0.5000 - loss: 0.8732
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - acc: 0.5000 - loss: 0.8602
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - acc: 0.5000 - loss: 0.8477
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - acc: 0.5000 - loss: 0.8356
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - acc: 0.5000 - loss: 0.8238
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - acc: 0.5000 - loss: 0.8125
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms

In [42]:
model.get_weights()

[array([[0.3214713],
        [0.5096403]], dtype=float32),
 array([-0.1498373], dtype=float32)]

In [43]:
# 모델평가
model.evaluate(data, label)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 218ms/step - acc: 1.0000 - loss: 0.0707


[0.07073843479156494, 1.0]

In [44]:
# 모델예측
result = model.predict(data)
print(result)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
[[-0.1498373 ]
 [ 0.171634  ]
 [ 0.35980296]
 [ 0.68127424]]


### 2. 단층 퍼셉트론 and 게이트

|x1|x2|y|
|---|---|---|
|0|0|0|
|1|0|0|
|0|1|0|
|1|1|1|

In [45]:
data = np.array([
    [0,0],
    [1,0],
    [0,1],
    [1,1]
])

label = np.array([0,0,0,1])

In [46]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(1,input_shape=(2,)))

In [47]:
model.compile(
    optimizer = "sgd",
    # optimizer = SGD()
    loss='mse',
    # loss = MSE()
    metrics = ["acc"]
)

In [48]:
model.fit(data,label,epochs=500,verbose=0)

In [49]:
model.get_weights()

[array([[0.51203674],
        [0.39529595]], dtype=float32),
 array([-0.19504184], dtype=float32)]

In [50]:
model.evaluate(data,label)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 233ms/step - acc: 1.0000 - loss: 0.0654


[0.06535134464502335, 1.0]

In [51]:
print(model.predict(data))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
[[-0.19504184]
 [ 0.3169949 ]
 [ 0.20025411]
 [ 0.7122908 ]]


### 3. xor 게이트

In [52]:
data = np.array([
    [0,0],
    [1,0],
    [0,1],
    [1,1]
])

label = np.array([0,1,1,0])

In [55]:
model = Sequential()
model.add(Dense(32,input_shape=(2,),activation="relu"))
model.add(Dense(1, activation='sigmoid'))

model.compile(
    optimizer=SGD(),
    # loss=MSE,
    loss='mse',
    metrics = ['acc']
)

In [56]:
model.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 32)             │            96 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 129 (516.00 B)

 Trainable params: 129 (516.00 B)

 Non-trainable params: 0 (0.00 B)

In [57]:
model.fit(data,label,epochs=500,verbose=1)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 525ms/step - acc: 0.5000 - loss: 0.2752
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - acc: 0.2500 - loss: 0.2750
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - acc: 0.2500 - loss: 0.2749
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - acc: 0.2500 - loss: 0.2747
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - acc: 0.2500 - loss: 0.2746
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - acc: 0.2500 - loss: 0.2745
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - acc: 0.2500 - loss: 0.2743
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step - acc: 0.2500 - loss: 0.2742
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - acc: 0.2500 - loss: 0.2740
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - acc: 0.2500 - loss: 0.2739
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - acc: 0.2500 - loss: 0.2737
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - acc: 0.2500 - loss: 0.2736
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/s

In [ ]:
model.evaluate(data,label)